// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezlxlgzxnywaunyinscn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bHhsZ3p4bnl3YXVueWluc2NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzI1ODIsImV4cCI6MjA3MTcwODU4Mn0.bPmxCgWNjayyhaaJQIODxrULllurI83nKRN3XsG15i0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});